name: Deploy to GitHub Pages

on:
  push:
    branches:
      - new-feat/migrate-reactjs

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Buat folder build-site sebagai tempat push ke gh-pages
          mkdir -p build-site
          cp -R dist/* build-site/
          
          cd build-site
          git init
          git checkout --orphan gh-pages
          git add .
          git commit -m "Deploy Vite site"
          
          # Push ke gh-pages dengan token bawaan GitHub Actions
          git push --force gh-pages
